ccaeServer:
    protocol: https
    host: ccae.manager.ctyun.cn
    port: 26335
    userName: lndxsy502cs
    userPassword: Lnsydx502cs@2024
    tokenTimeOut: 1800
ccaeAPIs:
    tokenUrl: /rest/plat/smapp/v1/oauth/token
    qureyTopoUrl: /api/monitor/v1/query-topo
mysqlConfig:
    user: root
    password: 930927
    address: 127.0.0.1:3306
    db: ctccl
elasticConfig:
    # 是否开启
    enable: true
    # 服务地址，多个地址用逗号隔开
    url: http://127.0.0.1:9200
    # 是否转换请求地址，默认为true,当等于true时 请求http://ip:port/_nodes/http，将其返回的url作为请求路径
    sniff: false
    # 心跳检测间隔
    healthcheckInterval: 5s
    # 日志前缀
    logPre: ES-




