elasticSearch:
    # 是否开启
    enable: true
    # 服务地址，多个地址用逗号隔开
    url: http://127.0.0.1:9200
    # 是否转换请求地址，默认为true,当等于true时 请求http://ip:port/_nodes/http，将其返回的url作为请求路径
    sniff: false
    # 心跳检测间隔
    healthcheckInterval: 5
    # 日志前缀
    logPre: ES-
    password: xwViJm3InjSCXAhN
    username: elastic
log: # 日志配置
    # 日志路径
    name: cwai-watcher
    level: debug
    traceLevel: error
    logToDir: .
    maxSizeInMiB: 10
    maxAgeInDays: 30
app:
    configFile: "./conf/config.yaml"
    port: "8081"
    host: "127.0.0.1"




