apiVersion: v1
kind: Service
metadata:
  name: cwai-event-service
  namespace: cwai
spec:
  ports:
  - name: cwai-event-service
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    k8s-app: cwai-event-service
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cwai-event-service
  namespace: cwai
data:
  config.yaml: |
    logger:
      name: cwai-event-service
      level: debug
      traceLevel: error
      logToDir: .
      maxSizeInMiB: 10
      maxAgeInDays: 30
    app:
      host: "0.0.0.0"
      port: "8081"
      configFile: "./conf/config.yaml"
    elasticSearch:
      # 是否开启
      enable: true
      # 服务地址，多个地址用逗号隔开
      url: https://127.0.0.1:9200
      # 是否转换请求地址，默认为true,当等于true时 请求http://ip:port/_nodes/http，将其返回的url作为请求路径
      sniff: false
      # 心跳检测间隔
      healthcheckInterval: 5
      # 日志前缀
      logPre: ES-
      password: xwViJm3InjSCXAhN
      username: elastic
    auth:
      authHost: http://cwai-workspace-service.cwai.svc:8080
      authPath: /apis/v1/workspace-service/workspace/userInfo


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cwai-event-service
  namespace: cwai
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: cwai-event-service
  template:
    metadata:
      labels:
        k8s-app: cwai-event-service
      name: cwai-event-service
    spec:
      containers:
      - image: shanghai15.ccr.ctyun.cn:15000/cbi/cwai-event-service:v1.0
        imagePullPolicy: Always
        name: cwai-event-service
        volumeMounts:
        - mountPath: /etc/cwai-event-service/config.yaml
          name: config
          subPath: config.yaml
      volumes:
      - configMap:
          defaultMode: 420
          name: cwai-event-service
        name: config


