apiVersion: v1
kind: Service
metadata:
  name: cwai-event-service
  namespace: cwai
spec:
  ports:
  - name: cwai-event-service
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    k8s-app: cwai-event-service
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cwai-event-service
  namespace: cwai
data:
  config.yaml: |
    logger:
      name: cwai-event-service
      level: debug
      traceLevel: error
      logToDir: .
      maxSizeInMiB: 10
      maxAgeInDays: 30
    app:
      host: 192.168.0.44
      port: 26335
      configFile: 
    elasticSearch:

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cwai-event-service
  namespace: cwai
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: cwai-event-service
  template:
    metadata:
      labels:
        k8s-app: cwai-event-service
      name: cwai-event-service
    spec:
      containers:
      - image: shanghai15.ccr.ctyun.cn:15000/cbi/cwai-event-service:v1.0
        imagePullPolicy: Always
        name: cwai-event-service
        volumeMounts:
        - mountPath: /etc/cwai-event-service/config.yaml
          name: config
          subPath: config.yaml
      volumes:
      - configMap:
          defaultMode: 420
          name: cwai-event-service
        name: config


