basePath: /ctccl
info:
  contact:
    email: yejianjun@ideal.sh.cn
    name: yejianjun
  description: 监听CTCCL上报事件服务
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: CTCCL事件监听
  version: "1.0"
paths: {}
swagger: "2.0"
