// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://example.com/terms/",
        "contact": {
            "name": "yejianjun",
            "url": "http://www.example.com/support",
            "email": "yejianjun@ideal.sh.cn"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/db/delete/{id}": {
            "delete": {
                "description": "通过ID从数据库删除事件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ctccl"
                ],
                "summary": "删除事件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "事件ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "数据删除成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid ID parameter",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Record not found!",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "数据删除失败",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/db/query": {
            "get": {
                "description": "查询所有事件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ctccl"
                ],
                "summary": "获取事件列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Event"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/db/query/{id}": {
            "get": {
                "description": "从数据库中通过 ID 获取特定事件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ctccl"
                ],
                "summary": "按 ID 查找事件",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/model.Event"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/db/save": {
            "post": {
                "description": "从数据库中创建一个新的事件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ctccl"
                ],
                "summary": "创建一个新的事件",
                "parameters": [
                    {
                        "description": "Event数据",
                        "name": "event",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Event"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/db/update/{id}": {
            "put": {
                "description": "根据id修改事件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ctccl"
                ],
                "summary": "修改事件",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "编辑参数",
                        "name": "event",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Event"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/es/delete/{id}": {
            "delete": {
                "description": "根据给定的ID删除ES中的事件",
                "tags": [
                    "ctccl"
                ],
                "summary": "删除ES中的事件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "事件ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功的消息",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "无效的ID消息",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "未找到记录的消息",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部服务器错误消息",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/es/page": {
            "post": {
                "description": "根据请求参数从ElasticSearch中分页获取事件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ctccl"
                ],
                "summary": "分页获取事件",
                "parameters": [
                    {
                        "description": "分页请求参数",
                        "name": "pageRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.EventPage"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.PageVo"
                        }
                    }
                }
            }
        },
        "/es/query/{id}": {
            "get": {
                "description": "通过ID从Elasticsearch中查找事件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ctccl"
                ],
                "summary": "查找事件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "事件ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/model.Event"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/es/save": {
            "post": {
                "description": "从请求中解析JSON并在Elasticsearch中存储一个新的事件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ctccl"
                ],
                "summary": "创建新的事件",
                "parameters": [
                    {
                        "description": "事件详情",
                        "name": "event",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Event"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "{\"message\": \"数据创建成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"invalid request\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"error\": \"internal server error\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/es/update/{id}": {
            "put": {
                "description": "更新来自Elasticsearch的事件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ctccl"
                ],
                "summary": "Update an event from Elasticsearch",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Event data",
                        "name": "event",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Event"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "common.PageVo": {
            "description": "分页响应结构",
            "type": "object",
            "properties": {
                "data": {
                    "description": "数据\n@json:\"data\""
                },
                "totalCount": {
                    "description": "总条数\n@json:\"totalCount,omitempty\"",
                    "type": "integer"
                },
                "totalPage": {
                    "description": "总页数\n@json:\"totalPage,omitempty\"",
                    "type": "integer"
                }
            }
        },
        "model.Event": {
            "description": "代表一个事件",
            "type": "object",
            "required": [
                "eventDetail",
                "eventType",
                "timestamp"
            ],
            "properties": {
                "eventDetail": {
                    "description": "EventDetail 事件详情\n@description 事件的详细信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.EventDetail"
                        }
                    ]
                },
                "eventType": {
                    "description": "EventType 事件类型\n@description 事件类型\n@example \"Error\"",
                    "type": "string"
                },
                "id": {
                    "description": "ID 事件的唯一标识符\n@description 事件的唯一标识符\n@example 1",
                    "type": "integer"
                },
                "level": {
                    "description": "Level 事件等级\n@description 事件等级\n@example \"High\"",
                    "type": "string"
                },
                "timestamp": {
                    "description": "Timestamp 时间戳\n@description 事件发生的时间戳\n@example \"2023-09-01T12:00:00Z\"",
                    "type": "string"
                }
            }
        },
        "model.EventDetail": {
            "description": "事件详情结构体",
            "type": "object",
            "required": [
                "localGuid",
                "remoteGuid"
            ],
            "properties": {
                "bandwidth": {
                    "description": "BandWidth 带宽Gb/s\nRequired: false",
                    "type": "integer",
                    "example": 10
                },
                "dataSize": {
                    "description": "DataSize 数据量（B）\nRequired: false",
                    "type": "integer",
                    "example": 1048576
                },
                "errorCode": {
                    "description": "ErrorCode 异常代码\nRequired: false",
                    "type": "integer",
                    "example": 100
                },
                "localGuid": {
                    "description": "LocalGuid 本端ib/roce设备nodegid\nRequired: true",
                    "type": "string",
                    "example": "local-guid-example"
                },
                "remoteGuid": {
                    "description": "RemoteGuid 对端ib/roce设备nodegid\nRequired: true",
                    "type": "string",
                    "example": "remote-guid-example"
                },
                "timeDuration": {
                    "description": "TimeDuration 时间间隔(ms)\nRequired: false",
                    "type": "integer",
                    "example": 500
                }
            }
        },
        "model.EventPage": {
            "description": "事件分页请求参数",
            "type": "object",
            "required": [
                "keyword",
                "time"
            ],
            "properties": {
                "keyword": {
                    "description": "关键词用于事件筛选\nrequired: true\nexample: \"连接错误\"",
                    "type": "string"
                },
                "page": {
                    "description": "Page 是页码。\nexample: 1\nrequired: true",
                    "type": "integer"
                },
                "size": {
                    "description": "Size 是每页条数。\nexample: 10\nrequired: true",
                    "type": "integer"
                },
                "time": {
                    "description": "事件发生的时间\nrequired: true\nexample: 2023-10-01T12:00:00Z",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/ctccl",
	Schemes:          []string{},
	Title:            "CTCCL事件监听",
	Description:      "监听CTCCL上报事件服务",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
