// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "yejianjun",
            "email": "yejianjun@ideal.sh.cn"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/query": {
            "get": {
                "description": "查询所有事件",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ctccl"
                ],
                "summary": "获取事件列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Event"
                            }
                        }
                    }
                }
            }
        },
        "/update/:id": {
            "put": {
                "description": "根据id修改事件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ctccl"
                ],
                "summary": "修改事件",
                "parameters": [
                    {
                        "description": "编辑参数",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Event"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "model.Event": {
            "type": "object",
            "required": [
                "eventDetail",
                "eventType",
                "timestamp"
            ],
            "properties": {
                "eventDetail": {
                    "description": "事件详情",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.EventDetail"
                        }
                    ]
                },
                "eventType": {
                    "description": "事件类型",
                    "type": "string"
                },
                "id": {
                    "description": "id",
                    "type": "integer"
                },
                "level": {
                    "description": "事件等级",
                    "type": "string"
                },
                "timestamp": {
                    "description": "时间戳",
                    "type": "string"
                }
            }
        },
        "model.EventDetail": {
            "type": "object",
            "required": [
                "localGuid",
                "remoteGuid"
            ],
            "properties": {
                "bandwidth": {
                    "description": "带宽Gb/s",
                    "type": "integer"
                },
                "dataSize": {
                    "description": "数据量（B）",
                    "type": "integer"
                },
                "errorCode": {
                    "description": "异常代码",
                    "type": "integer"
                },
                "localGuid": {
                    "description": "本端ib/roce设备nodegid",
                    "type": "string"
                },
                "remoteGuid": {
                    "description": "对端ib/roce设备nodegid",
                    "type": "string"
                },
                "timeDuration": {
                    "description": "时间间隔(ms)",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/ctccl",
	Schemes:          []string{},
	Title:            "CTCCL事件监听",
	Description:      "监听CTCCL上报事件服务",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
