basePath: /ctccl
definitions:
  common.CommonError:
    properties:
      code:
        type: integer
      msg:
        type: string
    type: object
  common.PageVo:
    description: 分页响应结构
    properties:
      data:
        description: |-
          数据
          @json:"data"
      totalCount:
        description: |-
          总条数
          @json:"totalCount,omitempty"
        type: integer
      totalPage:
        description: |-
          总页数
          @json:"totalPage,omitempty"
        type: integer
    type: object
  common.Response:
    description: 接口响应结构
    properties:
      code:
        description: |-
          响应代码
          Example: 200
        type: integer
      data:
        description: 响应数据
      message:
        description: |-
          响应消息
          Example: "请求成功"
          omitempty: 可选字段
        type: string
    type: object
  domain.EventPage:
    description: 该结构体用于指定事件分页查询时所需的参数。通过设置这些参数，可以灵活地获取所需的事件数据。
    properties:
      end_time:
        description: |-
          EndTime 事件的结束时间，应该晚于或等于 StartTime。
          格式为 "2006-01-02 15:04:05"。
          example: "2006-01-02 15:04:05"
          in: query
        type: string
      eventType:
        description: |-
          EventType 指定事件的类型。
          可以选择 "Critical", "Warning", 或 "Info"。
          example: "Critical"
          in: query
        enum:
        - Critical
        - Warning
        - Info
        type: string
      keyword:
        description: |-
          Keyword 用于筛选事件的关键词。
          例如可用于指定事件名称、描述中的特定短语。
          required: true
          example: "连接错误"
          in: query
        type: string
      nodeName:
        description: |-
          NodeName 节点名称，仅在事件的查询类型为节点时使用。
          对应于节点列表中的 instanceName。
          example: "node-01"
          in: query
        type: string
      page:
        description: |-
          Page 是页码。
          example: 1
          required: true
          in: query
        type: integer
      queryType:
        description: |-
          QueryType 用于指定查询的类型。
          该参数决定是查询节点事件（"node"）还是任务事件（"task"）。
          required: true
          example: "node"
          in: query
        enum:
        - node
        - task
        type: string
      regionID:
        description: |-
          RegionID 指定事件所属的区域ID。
          此参数用于限定事件的地理或逻辑区域。
          required: true
          example: "/central//elasticsearch/"
          in: query
        type: string
      resourceGroupID:
        description: |-
          ResourceGroupID 指定事件所属资源组的ID。
          用于组织和管理相关事件。
          required: true
          example: "rg-12345"
          in: query
        type: string
      size:
        description: |-
          Size 是每页条数。
          example: 10
          required: true
          in: query
        type: integer
      sort:
        description: |-
          Sort 指定排序类型，默认使用事件发生时间倒序。
          可选项，若不指定则使用默认排序。
          example: false
          optional: true
          in: query
        type: boolean
      start_time:
        description: |-
          StartTime 事件的开始时间。
          格式要求为 "2006-01-02 15:04:05"。
          required: true
          example: "2006-01-02 15:04:05"
          in: query
        type: string
      taskID:
        description: |-
          TaskID 指定任务的ID，仅在事件的查询类型为任务时为非空。
          仅当查询类型为任务时有效。
          example: "task-12345"
          in: query
        type: string
    required:
    - end_time
    - keyword
    - page
    - queryType
    - regionID
    - resourceGroupID
    - size
    - start_time
    type: object
host: localhost:8081
info:
  contact:
    email: yejianjun@ideal.sh.cn
    name: yejianjun
    url: http://www.example.com/support
  description: 监听CTCCL上报事件服务
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://example.com/terms/
  title: CTCCL事件监听
  version: "1.0"
paths:
  /es/page:
    post:
      consumes:
      - application/json
      description: 根据请求参数从ElasticSearch中分页获取事件。如果请求类型为"task"，则会执行事件搜索。
      parameters:
      - description: 分页请求参数，包括查询类型(queryType)和大小(size)
        in: body
        name: pageRequest
        required: true
        schema:
          $ref: '#/definitions/domain.EventPage'
      produces:
      - application/json
      responses:
        "200":
          description: 返回分页信息，包括总数(totalCount)、总页数(totalPage)、以及事件数据(data)
          schema:
            $ref: '#/definitions/common.PageVo'
        "400":
          description: 参数绑定失败
          schema:
            $ref: '#/definitions/common.CommonError'
        "404":
          description: 搜索数据失败
          schema:
            $ref: '#/definitions/common.CommonError'
      summary: 分页获取事件
      tags:
      - ctccl ES
  /es/query/{id}:
    get:
      consumes:
      - application/json
      description: 通过ID从Elasticsearch中查找和获取事件的信息
      parameters:
      - description: 事件的唯一标识符
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 返回成功时包含事件数据
          schema:
            $ref: '#/definitions/common.Response'
        "404":
          description: 未找到指定ID的事件
          schema:
            $ref: '#/definitions/common.Response'
      summary: 查找事件
      tags:
      - ctccl
      - Elasticsearch
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
