basePath: /ctccl
definitions:
  common.CommonError:
    properties:
      code:
        type: integer
      msg:
        type: string
    type: object
  common.PageVo:
    description: 分页响应结构体包含分页信息
    properties:
      data:
        description: |-
          数据
          @json:"data"
          @Description 当前页的数据
      pageNo:
        description: |-
          当前页码
          @json:"pageNo"
          @Description 当前页码
        type: integer
      totalCount:
        description: |-
          总条数
          @json:"totalCount,omitempty"
          @Description 总记录数
        type: integer
      totalPage:
        description: |-
          总页数
          @json:"totalPage,omitempty"
          @Description 总页数
        type: integer
    type: object
  model.EventPage:
    description: 该结构体用于指定事件分页查询时所需的参数。通过设置这些参数，可以灵活地获取符合条件的事件数据。
    properties:
      end:
        description: |-
          EndTime 事件的结束时间。
          以时间戳格式指定事件的截止筛选时间，应大于或等于 StartTime。
          in: query
          required: false
          example: 1625334000
        type: integer
      eventLike:
        description: |-
          EventLike 事件的模糊匹配关键词。
          通过关键词进行模糊搜索来进一步筛选事件。
          example: "error"
          in: query
        type: string
      eventType:
        description: |-
          EventType 指定要查询的事件类型。
          可选的类型包括 "Critical", "Warning", 或 "Info"。
          example: "Critical"
          in: query
        type: string
      nodeName:
        description: |-
          NodeName 节点名称。
          在查询类型为节点时使用，对应于节点列表中的 instanceName。
          example: "node-01"
          in: query
        type: string
      pageNo:
        description: |-
          PageNo 页码。
          指定请求的页码，页码从1开始。
          required: true
          in: query
          example: 1
        type: integer
      pageSize:
        description: |-
          PageSize 每页条数。
          指定每页返回的记录数。
          required: true
          in: query
          example: 20
        type: integer
      regionID:
        description: |-
          RegionID 指定事件所属区域的ID。
          此参数用于限定事件的地理或逻辑区域。
          required: true
          example: "/central//elasticsearch/"
          in: query
        type: string
      resourceGroupID:
        description: |-
          ResourceGroupID 指定事件所属资源组的ID。
          用于对事件进行组织和管理。
          required: true
          example: "rg-12345"
          in: query
        type: string
      sortType:
        description: |-
          SortType 排序类型。
          指定排序类型，默认按事件发生时间倒序。如不指定将使用默认排序。
          example: false
          in: query
        type: boolean
      start:
        description: |-
          StartTime 事件的开始时间。
          以时间戳格式指定事件的起始筛选时间。
          in: query
          required: false
          example: 1625247600
        type: integer
      taskID:
        description: |-
          TaskID 任务的ID。
          在查询类型为任务时使用，仅此时有效。
          example: "task-12345"
          in: query
        type: string
    type: object
host: localhost:8081
info:
  contact:
    email: yejianjun@ideal.sh.cn
    name: yejianjun
    url: http://www.example.com/support
  description: 监听CTCCL上报事件服务
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://example.com/terms/
  title: CTCCL事件监听
  version: "1.0"
paths:
  /apis/v1/cwai-event-service/list:
    post:
      consumes:
      - application/json
      description: 根据请求参数从ElasticSearch中分页获取事件。如果请求类型为"task"，则会执行事件搜索。
      parameters:
      - description: 分页请求参数，包括查询类型(queryType)和大小(size)
        in: body
        name: pageRequest
        required: true
        schema:
          $ref: '#/definitions/model.EventPage'
      produces:
      - application/json
      responses:
        "200":
          description: 返回分页信息，包括总数(totalCount)、总页数(totalPage)、以及事件数据(data)
          schema:
            $ref: '#/definitions/common.PageVo'
        "400":
          description: 参数绑定失败
          schema:
            $ref: '#/definitions/common.CommonError'
        "404":
          description: 搜索数据失败
          schema:
            $ref: '#/definitions/common.CommonError'
      summary: 分页获取事件
      tags:
      - events
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
